### ISSUE TITLE
Variable terminology: purnaviram/danda

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#19]
3. Text segmentation
http://w3c.github.io/ilreq/#h_text_segmentation

> purnaviram on double-click while in some browsers Danda is selected as a separate.

i think it would be clearer to readers to adopt one way of referring to this once it is established that danda and purnaviram are synonyms.

**Comment by slata** [comment]
The changes have been made in the draft as suggested.

**Comment by lianghai** [comment]
It's still there. It's really confusing to use multiple names to refer to these punctuations.

Basically, in Sanskrit, "।" is called _virāma_ ("stop"; sometimes _ardhavirām_, "half stop") and "॥" _pūrṇavirāma_ ("full stop"). Such usage-based names naturally get ambiguous when their usage changes, eg, in modern Hind text only "।" is used like western "." to terminate sentences (thus, full stop), and "," inside sentences.

I can understand it's Hindi's usage that led to such statement confusing to anyone who knows multiple Indic languages:

> In case of Devanagari phrase separator called **Danda** or **purnaviram** (।) and **double danda** (।।: used to mark end of the verse)…

Can we just use Unicode names or shape-based (instead of usage-based) names in such cases to reduce ambiguity? In such a doc that discusses multiple languages (which often have conflicting ways of naming things), it's important to stick a clear defined set of terminology.

**Comment by r12a** [comment]
+1 to @lianghai for consistent naming, and use of more general terminology where appropriate.  It would be useful to have a glossary  for these terms.  The glossary could usefully also give local names for things like the danda or virama.

**Comment by slata** [comment]
The changes has been made in the commit 5e4cfb8
